version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: gin-mania-postgres
    restart: unless-stopped
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
